命令稿啟動於 2017年03月12日 (週日) 14時46分07秒
]0;samcheng@samcheng-VirtualBox: ~/hw/lab1[01;32msamcheng@samcheng-VirtualBox[00m:[01;34m~/hw/lab1[00m$ whi[Koamu[Ki;pwd
samcheng
/home/samcheng/hw/lab1
]0;samcheng@samcheng-VirtualBox: ~/hw/lab1[01;32msamcheng@samcheng-VirtualBox[00m:[01;34m~/hw/lab1[00m$ git config-;[Kl
git: 'config-l' is not a git command. See 'git --help'.
]0;samcheng@samcheng-VirtualBox: ~/hw/lab1[01;32msamcheng@samcheng-VirtualBox[00m:[01;34m~/hw/lab1[00m$ git config-l l[1@ [C[C[1Pl
user.email=samcheng168@gmail.com
user.name=sam2377
core.editor=vim
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
remote.origin.url=https://github.com/sam2377/lab1.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.master.remote=origin
branch.master.merge=refs/heads/master
]0;samcheng@samcheng-VirtualBox: ~/hw/lab1[01;32msamcheng@samcheng-VirtualBox[00m:[01;34m~/hw/lab1[00m$ git config -l[K[K[K[K[K[K[K[K[Kclone https://gith ub.com/sam2377/lab1.git
Cloning into 'lab1'...
remote: Counting objects: 18, done.[K
remote: Compressing objects:   7% (1/13)   [Kremote: Compressing objects:  15% (2/13)   [Kremote: Compressing objects:  23% (3/13)   [Kremote: Compressing objects:  30% (4/13)   [Kremote: Compressing objects:  38% (5/13)   [Kremote: Compressing objects:  46% (6/13)   [Kremote: Compressing objects:  53% (7/13)   [Kremote: Compressing objects:  61% (8/13)   [Kremote: Compressing objects:  69% (9/13)   [Kremote: Compressing objects:  76% (10/13)   [Kremote: Compressing objects:  84% (11/13)   [Kremote: Compressing objects:  92% (12/13)   [Kremote: Compressing objects: 100% (13/13)   [Kremote: Compressing objects: 100% (13/13), done.[K
remote: Total 18 (delta 5), reused 12 (delta 3), pack-reused 0[K
Unpacking objects:   5% (1/18)   Unpacking objects:  11% (2/18)   Unpacking objects:  16% (3/18)   Unpacking objects:  22% (4/18)   Unpacking objects:  27% (5/18)   Unpacking objects:  33% (6/18)   Unpacking objects:  38% (7/18)   Unpacking objects:  44% (8/18)   Unpacking objects:  50% (9/18)   Unpacking objects:  55% (10/18)   Unpacking objects:  61% (11/18)   Unpacking objects:  66% (12/18)   Unpacking objects:  72% (13/18)   Unpacking objects:  77% (14/18)   Unpacking objects:  83% (15/18)   Unpacking objects:  88% (16/18)   Unpacking objects:  94% (17/18)   Unpacking objects: 100% (18/18)   Unpacking objects: 100% (18/18), done.
Checking connectivity... done.
]0;samcheng@samcheng-VirtualBox: ~/hw/lab1[01;32msamcheng@samcheng-VirtualBox[00m:[01;34m~/hw/lab1[00m$ ls
[0m[01;32m3n+1[0m      [01;34mlab1[0m         README
3n+1.cpp  lab1.script  running_script.script
]0;samcheng@samcheng-VirtualBox: ~/hw/lab1[01;32msamcheng@samcheng-VirtualBox[00m:[01;34m~/hw/lab1[00m$ exit

命令稿已於 2017年03月12日 (週日) 14時47分30秒
 完成
