命令稿啟動於 2017年03月07日 (週二) 22時41分23秒
]0;samcheng@samcheng-VirtualBox: ~[01;32msamcheng@samcheng-VirtualBox[00m:[01;34m~[00m$ whoamu[Ki;pwd
samcheng
/home/samcheng
]0;samcheng@samcheng-VirtualBox: ~[01;32msamcheng@samcheng-VirtualBox[00m:[01;34m~[00m$ git [K config0[K-l
git: 'config-l' is not a git command. See 'git --help'.
]0;samcheng@samcheng-VirtualBox: ~[01;32msamcheng@samcheng-VirtualBox[00m:[01;34m~[00m$ git config-l
git: 'config-l' is not a git command. See 'git --help'.
]0;samcheng@samcheng-VirtualBox: ~[01;32msamcheng@samcheng-VirtualBox[00m:[01;34m~[00m$ git init
Initialized empty Git repository in /home/samcheng/.git/
]0;samcheng@samcheng-VirtualBox: ~[01;32msamcheng@samcheng-VirtualBox[00m:[01;34m~[00m$ git status
On branch master

Initial commit

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	[31m.ICEauthority[m
	[31m.Xauthority[m
	[31m.bash_logout[m
	[31m.bashrc[m
	[31m.cache/[m
	[31m.config/[m
	[31m.dbus/[m
	[31m.dmrc[m
	[31m.gitconfig[m
	[31m.local/[m
	[31m.mozilla/[m
	[31m.presage/[m
	[31m.profile[m
	[31m.sudo_as_admin_successful[m
	[31m.viminfo[m
	[31m.vimrc[m
	[31m.xsession-errors[m
	[31mexamples.desktop[m
	[31mlab1.script[m
	[31mtesr.c[m

nothing added to commit but untracked files present (use "git add" to track)
]0;samcheng@samcheng-VirtualBox: ~[01;32msamcheng@samcheng-VirtualBox[00m:[01;34m~[00m$ git config [K-l
git: 'config-l' is not a git command. See 'git --help'.
]0;samcheng@samcheng-VirtualBox: ~[01;32msamcheng@samcheng-VirtualBox[00m:[01;34m~[00m$ git config-l -l
user.email=samcheng168@gmail.com
user.name=sam2377
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
]0;samcheng@samcheng-VirtualBox: ~[01;32msamcheng@samcheng-VirtualBox[00m:[01;34m~[00m$ git config -l[C[K[K[K[K[K[K[K[Kline[K[K[Kone http:[Ks://github.com/sam2377/lab1.git
Cloning into 'lab1'...
remote: Counting objects: 3, done.[K
remote: Total 3 (delta 0), reused 0 (delta 0), pack-reused 0[K
Unpacking objects:  33% (1/3)   Unpacking objects:  66% (2/3)   Unpacking objects: 100% (3/3)   Unpacking objects: 100% (3/3), done.
Checking connectivity... done.
]0;samcheng@samcheng-VirtualBox: ~[01;32msamcheng@samcheng-VirtualBox[00m:[01;34m~[00m$ exit

命令稿已於 2017年03月07日 (週二) 22時50分06秒
 完成